### ISSUE TITLE
Shrinking does not properly work when using choose with a range not containing 0

### ISSUE THREAD

**Issue by jgongo** [typelift/SwiftCheck#171]
Hi,

I'm using version 0.6.1 (downloaded using CocoaPods) of SwiftCheck in Mac OS X.

I'm trying to use SwiftCheck to check some properties related to periods in a year, for example using random values for the day in a given year (`Gen<Int>.choose((1, 365))`). When a property using such a generator fails I'm unable to get the value that caused the failure, apparently due to shrinking. From what I've seen, it seems that integers are shrunk dividing by two, so eventually any value will be shrunk to 0. The problem is that 0 is not in my valid range of values, so clearly 0 will make my test fail, giving me no valuable information about what really made the test fail.

Here you have a small test case I've prepared to illustrate the issue using Quick:

```
import Quick
import SwiftCheck


class ShrinkingFailureSpec: QuickSpec {
    override func spec() {
        context("shrinking in ranges containing 0") {
            let values = Gen<Int>.choose((0, 100))
            
            it("provides a valid failure example") {
                property("all values are inside the range") <- forAll(values) { (value: Int) in
                    0 <= value && value <= 50 // To deliberately make it fail
                }
            }
        }
        
        context("shrinking in ranges not containing 0") {
            let values = Gen<Int>.choose((50, 150))
            
            it("does not provide a valid failure example") {
                property("all values are inside the range") <- forAll(values) { (value: Int) in
                    50 <= value && value <= 100 // To deliberately make it fail
                }
            }
        }
    }
}
```

If you run that test you may get an output similar to the following:

```
Test Suite 'ShrinkingFailureSpec' started at 2016-08-12 17:01:36.861
Test Case '-[module.ShrinkingFailureSpec shrinking_in_ranges_containing_0__provides_a_valid_failure_example]' started.
*** Failed! Proposition: all values are inside the range
Falsifiable (after 1 test):
85
*** Passed 0 tests
.
/.../module/classes/ShrinkingFailureSpec.swift:19: error: -[module.ShrinkingFailureSpec shrinking_in_ranges_containing_0__provides_a_valid_failure_example] : failed - Falsifiable; Replay with 1399049737 8456 and size 0
Test Case '-[module.ShrinkingFailureSpec shrinking_in_ranges_containing_0__provides_a_valid_failure_example]' failed (0.006 seconds).
Test Case '-[module.ShrinkingFailureSpec shrinking_in_ranges_not_containing_0__provides_a_valid_failure_example]' started.
*** Failed! Proposition: all values are inside the range
Falsifiable (after 2 tests and 7 shrinks):
0
*** Passed 1 test
.
/.../module/classes/ShrinkingFailureSpec.swift:29: error: -[module.ShrinkingFailureSpec shrinking_in_ranges_not_containing_0__provides_a_valid_failure_example] : failed - Falsifiable; Replay with 428292667 344132242 and size 1
Test Case '-[module.ShrinkingFailureSpec shrinking_in_ranges_not_containing_0__provides_a_valid_failure_example]' failed (0.004 seconds).
Test Suite 'ShrinkingFailureSpec' failed at 2016-08-12 17:01:36.872.
	 Executed 2 tests, with 2 failures (0 unexpected) in 0.010 (0.012) seconds
```

As you can see the first test failure gives me a value (85) that is indeed inside the provided range and may make the property fail so I can further investigate the issue. In the second case I get 0 as the value to make my property fail, but that value is outside the range I'm testing, so it gives me no information about what really went wrong with the test.

It seems in the second case my only option is to replay the test with the given seeds and size and place a breakpoint to get the value that is really causing my test to fail, but that is really cumbersome when you have tests that randomly fail due to some edge cases.

**Comment by CodaFi** [comment]
You seem to think the shrinking mechanism has brains.  It really doesn't, and we make that clear in the documentation for `forAll`

> converts a function to a universally quantified property *using the default shrinker for that type*.

The default shrinker knows absolutely nothing about the generator's range of values.  It doesn't even know what a generator is!  You are definitely going to have to either forgo shrinking with `forAllNoShrink` or just write a simple wrapper type that conforms to `Arbitrary` with a shrinker that satisfies your invariants.  Either way, this is not an issue with SwiftCheck so I'm going to close this.  Feel free to reopen it if I've missed something here.
